id: agile-timer

about:
  title: agile-timer
  description: Your Project Description

contacts:
  humans: John Gallagher 

environments:
  - type: git
    title: Source Code
    uri: https://github.com/johngallagher/agile-timer
