version: 2.0
id: agile-timer
about:
  title: agile-timer
  description: Agile timer
contacts:
  - type: Developer
    name: John Gallagher
    email: john@synapticmishap.co.uk
environments:
  - type: git
    title: Source Code
    uri: https://github.com/johngallagher/agile-timer
  - type: production
    title: URL
    description: Web Application URL
    uri: https://www.acme.com
